service: planner-api
useDotenv: true

provider:
  name: aws
  runtime: nodejs22.x
  stage: ${opt:stage, 'dev'}
  versionFunctions: false
  region: ap-northeast-1
  timeout: 6

  environment:
    NODE_ENV: ${env:NODE_ENV}
    PORT: ${env:PORT}

custom:
  dotenv:
    exclude:
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
  includeDependencies:
    enableCaching: true

functions:
  app:
    handler: dist/lambda.handler
    events:
      - http:
          method: any
          path: /{proxy+}

package:
  excludeDevDependencies: true

plugins:
  - serverless-offline # Other plugins you may be using
  - serverless-dotenv-plugin
  - serverless-plugin-common-excludes # this should go before serverless-plugin-include-dependencies
  - serverless-plugin-include-dependencies
